// 自定义底栏：用 App 的自定义图标集（线性=未选 / 实心主题色=选中）
const D = 'data:image/svg+xml;base64,'
Component({
  data: {
    selected: 0,
    color: '#9098A1',
    selectedColor: '#2E9BEF',
    list: [
      {
        pagePath: '/pages/schedule/schedule',
        text: '课表',
        icon: D + 'PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgc3Ryb2tlPSIjOTA5OEExIiBzdHJva2Utd2lkdGg9IjIiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCI+PHBhdGggZD0iTTUuNSA1LjUgTDE4LjUgNS41IEEyIDIgMCAwIDEgMjAuNSA3LjUgTDIwLjUgMTkgQTIgMiAwIDAgMSAxOC41IDIxIEw1LjUgMjEgQTIgMiAwIDAgMSAzLjUgMTkgTDMuNSA3LjUgQTIgMiAwIDAgMSA1LjUgNS41IFoiLz48cGF0aCBkPSJNMy41IDkuNSBMMjAuNSA5LjUiLz48cGF0aCBkPSJNOCAzLjIgTDggNi4zIi8+PHBhdGggZD0iTTE2IDMuMiBMMTYgNi4zIi8+PHBhdGggZD0iTTcgMTMgTDkgMTMiLz48cGF0aCBkPSJNMTEgMTMgTDEzIDEzIi8+PHBhdGggZD0iTTE1IDEzIEwxNyAxMyIvPjxwYXRoIGQ9Ik03IDE3IEw5IDE3Ii8+PHBhdGggZD0iTTExIDE3IEwxMyAxNyIvPjwvc3ZnPg==',
        iconOn: D + 'PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgc3Ryb2tlPSIjMkU5QkVGIiBzdHJva2Utd2lkdGg9IjIiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCI+PHBhdGggZmlsbD0iIzJFOUJFRiIgZmlsbC1ydWxlPSJldmVub2RkIiBzdHJva2U9Im5vbmUiIGQ9Ik01LjUgNS41IEwxOC41IDUuNSBBMiAyIDAgMCAxIDIwLjUgNy41IEwyMC41IDE5IEEyIDIgMCAwIDEgMTguNSAyMSBMNS41IDIxIEEyIDIgMCAwIDEgMy41IDE5IEwzLjUgNy41IEEyIDIgMCAwIDEgNS41IDUuNSBaIE01IDguOCBMMTkgOC44IEwxOSA5LjYgTDUgOS42IFogTTYuNyAxMi4yIEw4LjcgMTIuMiBMOC43IDE0IEw2LjcgMTQgWiBNMTEgMTIuMiBMMTMgMTIuMiBMMTMgMTQgTDExIDE0IFogTTE1LjMgMTIuMiBMMTcuMyAxMi4yIEwxNy4zIDE0IEwxNS4zIDE0IFogTTYuNyAxNiBMOC43IDE2IEw4LjcgMTcuOCBMNi43IDE3LjggWiBNMTEgMTYgTDEzIDE2IEwxMyAxNy44IEwxMSAxNy44IFoiLz48cGF0aCBkPSJNOCAzLjIgTDggNiIvPjxwYXRoIGQ9Ik0xNiAzLjIgTDE2IDYiLz48L3N2Zz4=',
      },
      {
        pagePath: '/pages/grade/grade',
        text: '成绩',
        icon: D + 'PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgc3Ryb2tlPSIjOTA5OEExIiBzdHJva2Utd2lkdGg9IjIiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCI+PHBhdGggZD0iTTMuOCAyMCBMMjAuMiAyMCIvPjxwYXRoIGQ9Ik03IDIwIEw3IDE0LjUiLz48cGF0aCBkPSJNMTIgMjAgTDEyIDEwLjUiLz48cGF0aCBkPSJNMTcgMjAgTDE3IDYuNSIvPjwvc3ZnPg==',
        iconOn: D + 'PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgc3Ryb2tlPSIjMkU5QkVGIiBzdHJva2Utd2lkdGg9IjIiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCI+PHBhdGggZmlsbD0iIzJFOUJFRiIgc3Ryb2tlPSJub25lIiBkPSJNNS42IDIwIEw1LjYgMTYgQTEuNCAxLjQgMCAwIDEgOC40IDE2IEw4LjQgMjAgWiIvPjxwYXRoIGZpbGw9IiMyRTlCRUYiIHN0cm9rZT0ibm9uZSIgZD0iTTEwLjYgMjAgTDEwLjYgMTEuNSBBMS40IDEuNCAwIDAgMSAxMy40IDExLjUgTDEzLjQgMjAgWiIvPjxwYXRoIGZpbGw9IiMyRTlCRUYiIHN0cm9rZT0ibm9uZSIgZD0iTTE1LjYgMjAgTDE1LjYgNyBBMS40IDEuNCAwIDAgMSAxOC40IDcgTDE4LjQgMjAgWiIvPjxwYXRoIGQ9Ik0zLjggMjAuMiBMMjAuMiAyMC4yIi8+PC9zdmc+',
      },
      {
        pagePath: '/pages/profile/profile',
        text: '我的',
        icon: D + 'PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgc3Ryb2tlPSIjOTA5OEExIiBzdHJva2Utd2lkdGg9IjIiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCI+PHBhdGggZD0iTTguNiA4LjUgQTMuNCAzLjQgMCAxIDAgMTUuNCA4LjUgQTMuNCAzLjQgMCAxIDAgOC42IDguNSBaIi8+PHBhdGggZD0iTTUuMiAxOS42IEE2LjggNi44IDAgMCAxIDE4LjggMTkuNiIvPjwvc3ZnPg==',
        iconOn: D + 'PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgc3Ryb2tlPSIjMkU5QkVGIiBzdHJva2Utd2lkdGg9IjIiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCI+PHBhdGggZmlsbD0iIzJFOUJFRiIgc3Ryb2tlPSJub25lIiBkPSJNOC4zIDggQTMuNyAzLjcgMCAxIDAgMTUuNyA4IEEzLjcgMy43IDAgMSAwIDguMyA4IFoiLz48cGF0aCBmaWxsPSIjMkU5QkVGIiBzdHJva2U9Im5vbmUiIGQ9Ik00LjggMjAgQTcuMiA2LjIgMCAwIDEgMTkuMiAyMCBaIi8+PC9zdmc+',
      },
    ],
  },
  methods: {
    switchTab(e) {
      const i = e.currentTarget.dataset.index
      const path = this.data.list[i].pagePath
      wx.switchTab({ url: path })
    },
  },
})
