#!/usr/bin/env python3
"""Generate the Compose icon family and portable SVGs from design/icons.json.

No third-party packages required. Run from any directory; --check verifies exports.
The brand is four offset course blocks on a pure white background.
"""
import argparse
import json
from math import cos, radians, sin
from pathlib import Path
from xml.sax.saxutils import escape

ROOT = Path(__file__).resolve().parents[1]
RES = ROOT / "app/src/main/res"
ICONS = json.loads((ROOT / "design/icons.json").read_text())
STROKE = 1.75
# Product requirement: the standard app icon and in-app logo have a pure white base.
ICON_BACKGROUND = "#FFFFFF"
BLUE = "#3564DC"
SKY = "#9EBFFC"
APRICOT = "#F2A77D"


def course_block(x, y, width, height, radius):
    """Bake a gentle -12 degree tilt into paths shared by SVG and Android."""
    angle = radians(-12)
    curve = radius * 0.55228475

    def point(px, py):
        dx, dy = px - 54, py - 54
        return f"{54 + dx * cos(angle) - dy * sin(angle):.3f},{54 + dx * sin(angle) + dy * cos(angle):.3f}"

    def command(kind, *points):
        return kind + " ".join(point(px, py) for px, py in points)

    right, bottom = x + width, y + height
    return "".join([
        command("M", (x + radius, y)),
        command("L", (right - radius, y)),
        command("C", (right - radius + curve, y), (right, y + radius - curve), (right, y + radius)),
        command("L", (right, bottom - radius)),
        command("C", (right, bottom - radius + curve), (right - radius + curve, bottom), (right - radius, bottom)),
        command("L", (x + radius, bottom)),
        command("C", (x + radius - curve, bottom), (x, bottom - radius + curve), (x, bottom - radius)),
        command("L", (x, y + radius)),
        command("C", (x, y + radius - curve), (x + radius - curve, y), (x + radius, y)),
        "Z",
    ])


# Long lessons and short intervals form a compact, asymmetric rhythm.
# White space separates all four pieces, including in monochrome exports.
BRAND = [
    (BLUE, course_block(29, 28, 35, 23, 9)),
    (APRICOT, course_block(69, 28, 14, 23, 7)),
    (SKY, course_block(25, 56, 14, 23, 7)),
    (BLUE, course_block(44, 56, 35, 23, 9)),
]


def svg_paths(icon):
    parts = []
    for kind, paths in (("fills", icon.get("fills", [])), ("cutouts", icon.get("cutouts", [])), ("strokes", icon.get("strokes", []))):
        attrs = f'fill="none" stroke="currentColor" stroke-width="{STROKE}" stroke-linecap="round" stroke-linejoin="round"' if kind == "strokes" else 'fill="currentColor"' + (' fill-rule="evenodd"' if kind == "cutouts" else '')
        parts.extend(f'  <path d="{escape(d)}" {attrs}/>' for d in paths)
    return "\n".join(parts)


def vector(paths, size=108, viewport=108, translation=0, scale=1):
    body = "\n".join(f'    <path android:fillColor="{color}" android:pathData="{d}"/>' for color, d in paths)
    if scale != 1:
        body = f'    <group android:pivotX="54" android:pivotY="54" android:scaleX="{scale}" android:scaleY="{scale}">\n{body}\n    </group>'
    if translation:
        body = f'    <group android:translateX="{translation}" android:translateY="{translation}">\n{body}\n    </group>'
    return ('<?xml version="1.0" encoding="utf-8"?>\n'
            f'<vector xmlns:android="http://schemas.android.com/apk/res/android" android:width="{size}dp" android:height="{size}dp" android:viewportWidth="{viewport}" android:viewportHeight="{viewport}">\n'
            + body + '\n</vector>\n')


def outputs():
    generated = {}
    declarations = []
    for name, icon in ICONS.items():
        args = [f'"{name}"']
        for key in ("strokes", "fills", "cutouts"):
            if icon.get(key):
                args.append(key + " = listOf(\n" + ",\n".join("            " + json.dumps(d) for d in icon[key]) + "\n        )")
        if icon.get("mirror"):
            args.append("autoMirror = true")
        declarations.append(f'    /** {icon["label"]} */\n    val {name}: ImageVector by lazy {{\n        build(' + ",\n        ".join(args) + ")\n    }")
        generated[ROOT / f"design/svg/{name}.svg"] = ('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" role="img">\n'
            f'  <title>{icon["label"]}</title>\n' + svg_paths(icon) + '\n</svg>\n')

    catalog = ",\n".join(f'        "{icon["label"]}" to {name}' for name, icon in ICONS.items())
    generated[ROOT / "app/src/main/java/edu/csuft/sap/ui/icons/AppIcons.kt"] = '''package edu.csuft.sap.ui.icons

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.StrokeJoin
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.PathParser
import androidx.compose.ui.unit.dp

// Generated by scripts/generate_icons.py. Edit design/icons.json, then regenerate.
// 24dp grid · 1.75dp rounded strokes · shared geometry for SVG and native Compose.
object AppIcons {
    private fun build(
        name: String,
        strokes: List<String> = emptyList(),
        fills: List<String> = emptyList(),
        cutouts: List<String> = emptyList(),
        autoMirror: Boolean = false,
    ): ImageVector = ImageVector.Builder(
        name = name, defaultWidth = 24.dp, defaultHeight = 24.dp,
        viewportWidth = 24f, viewportHeight = 24f, autoMirror = autoMirror,
    ).apply {
        fills.forEach { d -> addPath(
            pathData = PathParser().parsePathString(d).toNodes(), fill = SolidColor(Color.Black),
        ) }
        cutouts.forEach { d -> addPath(
            pathData = PathParser().parsePathString(d).toNodes(),
            fill = SolidColor(Color.Black), pathFillType = PathFillType.EvenOdd,
        ) }
        strokes.forEach { d -> addPath(
            pathData = PathParser().parsePathString(d).toNodes(),
            stroke = SolidColor(Color.Black), strokeLineWidth = 1.75f,
            strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round,
        ) }
    }.build()

''' + "\n\n".join(declarations) + '\n\n    val catalog: List<Pair<String, ImageVector>> by lazy { listOf(\n' + catalog + '\n    ) }\n}\n'

    # Full mark used inside the app; adaptive foreground deliberately stays in the safe zone.
    tile = (ICON_BACKGROUND, "M26 0H82A26 26 0 0 1 108 26V82A26 26 0 0 1 82 108H26A26 26 0 0 1 0 82V26A26 26 0 0 1 26 0Z")
    generated[RES / "drawable/app_logo.xml"] = vector([tile] + BRAND)
    generated[RES / "drawable/ic_launcher_foreground.xml"] = vector(BRAND, scale=0.88)
    generated[RES / "drawable/ic_launcher_monochrome.xml"] = vector([("#FFFFFF", d) for _, d in BRAND], scale=0.88)
    generated[RES / "drawable/ic_notification.xml"] = vector(
        [("#FFFFFF", d) for _, d in BRAND], size=24, viewport=72, translation=-18,
    )
    generated[RES / "values/colors_launcher.xml"] = f'<?xml version="1.0" encoding="utf-8"?>\n<resources>\n    <color name="ic_launcher_bg">{ICON_BACKGROUND}</color>\n</resources>\n'
    for api in (26, 33):
        for name in ("ic_launcher", "ic_launcher_round"):
            generated[RES / f"mipmap-anydpi-v{api}/{name}.xml"] = ('<?xml version="1.0" encoding="utf-8"?>\n'
                '<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">\n'
                '    <background android:drawable="@color/ic_launcher_bg"/>\n'
                '    <foreground android:drawable="@drawable/ic_launcher_foreground"/>\n'
                + ('    <monochrome android:drawable="@drawable/ic_launcher_monochrome"/>\n' if api >= 33 else '')
                + '</adaptive-icon>\n')
    generated[ROOT / "design/app-icon.svg"] = ('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 108 108" role="img">\n'
        '  <title>软协课表 · 课间节奏</title>\n' + "\n".join(f'  <path fill="{c}" d="{d}"/>' for c, d in [tile] + BRAND) + '\n</svg>\n')
    for name in ("Schedule", "Grades", "Profile", "Academic", "Web", "ClassGroup", "Refresh"):
        refresh = name == "Refresh"
        animation = "spin 1.2s linear infinite" if refresh else "arrive .28s cubic-bezier(.2,.8,.2,1) both"
        keyframes = "@keyframes spin{to{transform:rotate(360deg)}}" if refresh else "@keyframes arrive{from{opacity:.35;transform:translateY(1px) scale(.9)}to{opacity:1;transform:none}}"
        generated[ROOT / f"design/svg/{name}Animated.svg"] = ('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" role="img">\n'
            f'<title>{ICONS[name]["label"]} · 动态</title>\n'
            f'<style>g{{transform-origin:12px 12px;animation:{animation}}}{keyframes}@media(prefers-reduced-motion:reduce){{g{{animation:none}}}}</style>\n'
            '<g>\n' + svg_paths(ICONS[name]) + '\n</g>\n</svg>\n')
    return generated


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale = []
    for path, content in outputs().items():
        if args.check:
            if not path.exists() or path.read_text() != content:
                stale.append(str(path.relative_to(ROOT)))
        else:
            if not path.exists() or path.read_text() != content:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content)
    if stale:
        raise SystemExit("Stale generated assets:\n" + "\n".join(stale))
    print(f'{len(ICONS)} icons + brand + animated SVGs: {"verified" if args.check else "generated"}')
