const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require('/Users/pllysun/Library/Caches/ms-playwright-go/1.57.0/package');
const session=JSON.parse(fs.readFileSync('/Users/pllysun/Library/Caches/sap-oj-test-session.json'));
const production=process.env.SAP_OJ_PRODUCTION==='true',base=process.env.SAP_BASE_URL||'http://127.0.0.1:18081';
const shots='/Users/pllysun/Library/Caches/sap-oj-ui';
async function main(){
 const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});
 try{
 const page=await browser.newPage({viewport:{width:1440,height:1050}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(token=>{localStorage.setItem('sap_token',token);localStorage.setItem('sap-token',token)},session.token);
 const api=async route=>(await(await fetch(session.base+route,{headers:{'sap-token':session.token}})).json()).data;
 if(!production){
   const local={id:'1',name:'容器内置节点',endpoint:'http://127.0.0.1:5051',builtin:true,enabled:true,online:true,state:'RUNNING',capacity:1,maxConcurrency:1,active:0,freeSlots:1,cpuPercent:17,memoryUsedMb:72,memoryMb:640,hostAvailableMb:723,cpuCores:1,lastSeen:Date.now()};
   await page.route('**/api/oj/runtime',r=>r.fulfill({json:{code:200,data:{available:true,freeSlots:1,capacity:1}}}));
   await page.route('**/api/admin/oj/nodes',r=>r.fulfill({json:{code:200,data:{nodes:[local,{...local,id:'2',name:'独立服务器',endpoint:'https://judge.example.com',builtin:false,online:false,enabled:false,state:'OFFLINE',capacity:4,maxConcurrency:4,cpuCores:4,memoryMb:2560,freeSlots:0}],online:1,capacity:1,availableSlots:local.freeSlots}}}));
   await page.route(/\/api\/admin\/oj\/nodes\/1\/(stop|start)$/,async r=>{const start=r.request().url().endsWith('/start');local.state=start?'STARTING':'STOPPING';local.enabled=start;local.freeSlots=0;await r.fulfill({json:{code:200,data:local}});setTimeout(()=>{local.state=start?'RUNNING':'STOPPED';local.freeSlots=start?1:0;local.memoryUsedMb=start?72:0},250)});
   await page.route(/\/api\/admin\/oj\/monitor\/\d+\/code$/,async r=>{const id=r.request().url().split('/').at(-2),job=await api('/api/admin/oj/jobs/'+id);await r.fulfill({json:{code:200,data:{code:job.code,language:job.language,mode:job.mode}}})});
 }
 await page.goto(base+'/oj');await page.locator('.oj-problem-row').first().waitFor();assert(await page.getByRole('heading',{name:'算法题库',exact:true}).isVisible());
 for(const width of [390,768,1024,1440,1920]){await page.setViewportSize({width,height:1050});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'library overflow '+width);if([390,1440].includes(width))await page.screenshot({path:path.join(shots,'new-library-'+width+'.png'),fullPage:true})}
 await page.getByRole('tab',{name:'提交记录',exact:true}).click();await page.locator('.oj-submission-summary').first().waitFor();assert.equal(await page.locator('.oj-difficulty-progress').first().locator(':scope>div').count(),3);
 const problem=(await api('/api/oj/problems')).records.find(p=>p.slug==='leetcode-1');await page.goto(base+'/oj/'+problem.id);await page.locator('.cm-content').first().waitFor();await page.waitForFunction(()=>!document.querySelector('.oj-template-loading'));
 for(const width of [390,768,1024,1440,1920]){await page.setViewportSize({width,height:1050});if(width<=800)await page.getByRole('button',{name:'代码与控制台',exact:true}).click();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'workspace overflow '+width);if([390,1440].includes(width))await page.screenshot({path:path.join(shots,'new-workspace-'+width+'.png'),fullPage:true})}
 await page.setViewportSize({width:1440,height:1050});await page.getByRole('button',{name:'专注写代码 ↗',exact:true}).click();assert.equal(await page.locator('.oj-statement').isVisible(),false);await page.getByRole('button',{name:'返回双栏',exact:true}).click();assert(await page.locator('.oj-statement').isVisible());
 await page.getByRole('button',{name:'我的提交记录',exact:true}).click();await page.locator('.oj-history-row').first().click();await page.getByRole('button',{name:'查看提交代码',exact:true}).click();assert(await page.locator('.oj-submitted-code .cm-content').isVisible());

 if(production){await page.getByRole('button',{name:'我的提交记录',exact:true}).click();await page.locator('.oj-history-row').filter({hasText:'正式提交'}).filter({hasText:'通过'}).first().click();await page.locator('.oj-histogram').first().waitFor();assert.equal(await page.locator('.oj-histogram').count(),2);assert.equal(await page.locator('.oj-histogram>div').count(),16);for(const width of [390,768,1440]){await page.setViewportSize({width,height:1050});if(width<=800)await page.getByRole('button',{name:'代码与控制台',exact:true}).click();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'performance overflow '+width)}await page.setViewportSize({width:1440,height:1050});await page.getByRole('button',{name:'本题排行',exact:true}).click();await page.locator('.oj-problem-ranking .oj-ranking-row').first().waitFor();}
 await page.goto(base+'/admin/oj');await page.getByRole('tab',{name:'统一管理',exact:true}).click();await page.locator('.node-card').first().waitFor();assert(await page.getByRole('heading',{name:'判题节点',exact:true}).isVisible());
 if(!production){await page.getByRole('button',{name:'停止节点',exact:true}).first().click();await page.locator('.node-state').filter({hasText:'已停止'}).first().waitFor({timeout:10000});await page.getByRole('button',{name:'启动节点',exact:true}).first().click();await page.locator('.node-state').filter({hasText:'运行中'}).first().waitFor({timeout:10000});}
 for(const width of [390,768,1024,1440]){await page.setViewportSize({width,height:1050});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'node manager overflow '+width);if([390,1440].includes(width))await page.screenshot({path:path.join(shots,'node-manager-'+width+'.png'),fullPage:true})}
 await page.getByRole('button',{name:'添加独立节点',exact:true}).click();await page.getByRole('dialog',{name:'添加独立判题节点'}).waitFor();assert.equal(await page.locator('input[type=password]').count(),1);await page.getByRole('button',{name:'取消',exact:true}).click();
 await page.getByRole('tab',{name:'判题日志与队列',exact:true}).click();await page.locator('.oj-runtime-table tbody tr').first().waitFor();await page.getByRole('button',{name:/查看过程/}).first().click();await page.getByRole('button',{name:'提交的代码',exact:true}).click();await page.locator('.oj-run-code .cm-content').waitFor();assert((await page.locator('.oj-run-code .cm-content').innerText()).length>0);
 assert.deepEqual(errors,[]);const report={passed:true,production,widths:[390,768,1024,1440,1920],checks:['redesigned problem list and submission board','responsive workspace and focus mode','own saved submission source',...(production?['performance histograms and per-problem ranking']:[]),'node resource monitoring',...(production?[]:['node control interactions']),'admin source viewer','password field for node token'],runtimeErrors:0};fs.writeFileSync(path.join(__dirname,'nodes-ui-'+(production?'production':'candidate')+'.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));
 }finally{await browser.close()}
}
main().catch(e=>{console.error(e.stack);process.exitCode=1});
