const fs=require('node:fs'),assert=require('node:assert/strict'),path=require('node:path')
const {chromium}=require('/Users/pllysun/Library/Caches/ms-playwright-go/1.57.0/package')
const session=JSON.parse(fs.readFileSync('/Users/pllysun/Library/Caches/sap-oj-test-session.json')),base=process.env.SAP_BASE_URL||session.base
const screenshotRoot='/Users/pllysun/Library/Caches/sap-oj-ui';fs.mkdirSync(screenshotRoot,{recursive:true})
async function main(){
 const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true})
 const errors=[];const api=async route=>(await(await fetch(base+route,{headers:{'sap-token':session.token}})).json()).data
 try{
 const user=await api('/api/auth/info'),problems=await api('/api/oj/problems');assert(problems.records.length>=2)
 const page=await browser.newPage({viewport:{width:1440,height:1000}});page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(({token,adminToken,user})=>{localStorage.setItem('sap_token',token);localStorage.setItem('sap-token',adminToken);localStorage.setItem('sap-user',JSON.stringify(user))},{token:session.userToken||session.token,adminToken:session.token,user})
 await page.goto(base+'/oj');await page.getByRole('heading',{name:'算法题库',exact:true}).waitFor();await page.locator('.oj-problem-row').first().waitFor()
 for(const width of [390,1024,1440]){await page.setViewportSize({width,height:1000});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'List overflow '+width)}
 const lc=problems.records.find(p=>p.slug==='leetcode-1');await page.goto(base+'/oj/'+lc.id);await page.locator('.cm-content').waitFor();await page.waitForFunction(()=>!document.querySelector('.oj-template-loading'));assert.equal(await page.getByRole('group',{name:'做题模式',exact:true}).getByRole('button',{name:'核心函数',exact:true}).getAttribute('aria-pressed'),'true');await page.getByRole('button',{name:'编程语言',exact:true}).click();assert.equal(await page.getByRole('option').count(),5);await page.keyboard.press('Escape')
 await page.getByRole('group',{name:'做题模式',exact:true}).getByRole('button',{name:'完整程序',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('.oj-template-loading'));await page.getByRole('button',{name:'编程语言',exact:true}).click();await page.getByRole('option').filter({hasText:'CPython'}).click();await page.waitForFunction(()=>!document.querySelector('.oj-template-loading'));await page.locator('.cm-content').click();await page.keyboard.press('Meta+A');await page.keyboard.insertText('print("draft verification")');await page.waitForTimeout(700);await page.reload();await page.locator('.cm-content').waitFor();await page.getByRole('group',{name:'做题模式',exact:true}).getByRole('button',{name:'完整程序',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('.oj-template-loading'));await page.getByRole('button',{name:'编程语言',exact:true}).click();await page.getByRole('option').filter({hasText:'CPython'}).click();await page.waitForFunction(()=>!document.querySelector('.oj-template-loading'));assert((await page.locator('.cm-content').innerText()).includes('draft verification'))
 const pack=JSON.parse(fs.readFileSync(path.join(__dirname,'problem-packs/leetcode-1/pack.json')));await page.locator('.cm-content').click();await page.keyboard.press('Meta+A');await page.keyboard.insertText(pack.references.python.STDIO);await Promise.all([page.waitForResponse(r=>r.url().endsWith('/api/oj/run')&&r.request().method()==='POST'),page.getByRole('button',{name:'运行代码',exact:true}).click()]);await page.locator('.oj-verdict.success').waitFor({timeout:120000});assert.equal(await page.locator('.oj-case-result').count(),1);assert((await page.getByRole('tablist',{name:'测试用例结果'}).getByRole('tab').count())>1);await page.getByRole('tablist',{name:'测试用例结果'}).getByRole('tab').nth(1).click();assert.equal(await page.getByRole('tablist',{name:'测试用例结果'}).getByRole('tab').nth(1).getAttribute('aria-selected'),'true')
 await Promise.all([page.waitForResponse(r=>r.url().endsWith('/api/oj/submit')&&r.request().method()==='POST'),page.getByRole('button',{name:'提交判题',exact:true}).click()]);await page.locator('.oj-verdict.success').waitFor({timeout:120000});assert.equal(await page.locator('.oj-case-result').count(),0)
 await page.getByRole('button',{name:'我的提交记录',exact:true}).click();await page.locator('.oj-history-row').first().waitFor()
 for(const width of [1440,1024,390]){await page.setViewportSize({width,height:1000});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Workspace overflow '+width);if(width===390){await page.getByRole('button',{name:'代码与控制台',exact:true}).click();assert(await page.locator('.cm-content').isVisible())}await page.screenshot({path:path.join(screenshotRoot,'workspace-'+width+'.png'),fullPage:true})}
 await page.setViewportSize({width:1440,height:1000});await page.goto(base+'/admin/oj');await page.getByRole('heading',{name:'算法题库',exact:true}).waitFor();await page.locator('.el-table__body-wrapper tbody tr').first().waitFor();await page.screenshot({path:path.join(screenshotRoot,'admin.png'),fullPage:true})
 await page.getByRole('tab',{name:'统一管理',exact:true}).click();assert.equal(await page.locator('.el-table__body-wrapper:visible tbody tr').count(),5);assert((await page.locator('body').innerText()).includes('OpenJDK 27'))
 await page.getByRole('tab',{name:'题目管理',exact:true}).click();await page.getByRole('button',{name:'测试集',exact:true}).first().click();await page.getByRole('tab',{name:/^测试集/}).waitFor();await page.getByRole('tab',{name:'语言模板与参考解',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('.oj-format-loading'));assert((await page.locator('.el-dialog .cm-content').count())>0);await page.getByRole('button',{name:'取消',exact:true}).click()
 assert.deepEqual(errors,[]);const report={passed:true,runtimeErrors:0,widths:[390,1024,1440],checks:['list','two modes','five language dropdown options','mode buttons','formatted starter and admin code editor','code draft persistence','sample run','hidden tests submit','history','admin tests editor','language settings']};fs.writeFileSync(path.join(__dirname,process.env.SAP_OJ_PRODUCTION==='true'?'browser-production-validation.json':'browser-candidate-validation.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report))
 }finally{await browser.close()}
}
main().catch(e=>{console.error(e.stack);process.exitCode=1})
