<template>
  <div class="page oj-set-detail oj-studio">
    <router-link to="/oj?tab=sets" class="oj-back"><UiIcon name="chevron-left" />算法题库 / 题单</router-link>
    <p v-if="error" class="oj-error" role="alert">{{ error }} <button class="btn btn--sm" @click="load">重试</button></p>
    <div v-if="loading" class="loading"><div class="loading__spinner" /></div>
    <template v-else-if="set">
      <PageHeader :title="set.name" label="" class="oj-set-hero"><template #body>
      <section class="oj-set-info"><div><span :class="['oj-set-chip',set.mode.toLowerCase()]">{{ set.mode==='CONTEST'?'比赛模式':'练习模式' }}</span><span :class="['oj-set-phase',set.phase.toLowerCase()]"><i />{{ phases[set.phase] }}</span><span>{{ set.total }} 道题 · {{ set.participants }} 人参与</span></div><p v-if="set.description" class="oj-prose">{{ set.description }}</p><div v-if="set.mode==='CONTEST'" class="oj-set-time"><span>北京时间 {{ date(set.startsAt) }} — {{ date(set.endsAt) }}</span><strong v-if="['UPCOMING','RUNNING'].includes(set.phase)" class="oj-set-countdown">{{ set.phase==='UPCOMING'?'距开赛':'剩余' }} {{ countdown }}</strong></div><p class="oj-set-rule">{{ set.mode==='PRACTICE'?'不限提交次数；题单参与者可查看正式提交的代码。':'按通过题数、总罚时排名；首次 AC 前每次有效失败罚时 20 分钟，编译错误及系统错误不罚时。' }}</p><div class="oj-set-join"><span v-if="set.disqualified" class="oj-error">已取消参与资格</span><span v-else-if="set.joined">{{ set.mode==='CONTEST'?'已报名':'已加入' }} · 已通过 {{ set.acCount }} / {{ set.total }}</span><span v-else-if="set.mode==='CONTEST'&&!set.canJoin">未报名，无法提交</span><button v-if="!set.joined&&set.canJoin" class="btn btn--primary" :disabled="joining" @click="join">{{ joining?'处理中…':set.mode==='CONTEST'?'报名比赛':'加入练习' }}</button><button class="btn btn--secondary" :disabled="refreshing" @click="refresh"><UiIcon name="refresh" :size="13" />刷新</button></div></section>
      </template></PageHeader>
      <div class="oj-library-tabs" role="tablist" aria-label="题单视图"><button v-for="t in tabs" :key="t.value" role="tab" :aria-selected="tab===t.value" :class="{active:tab===t.value}" @click="chooseTab(t.value)">{{ t.label }}</button></div>
      <template v-if="tab==='problems'"><div v-if="set.joined && activeItems.length" class="oj-set-resume"><div><UiIcon name="clipboard-check" :size="16" /><span>题单进度</span><strong>{{ set.acCount }} / {{ set.total }}</strong><div class="oj-progress-track"><i :style="{width:progress(set.acCount,set.total)+'%'}" /></div></div><router-link v-if="resumeItem && set.canSubmit" :to="`/oj/sets/${set.id}/items/${resumeItem.id}`">{{ set.mode==='CONTEST'?'继续比赛':'继续练习' }} · {{ resumeItem.label }} {{ resumeItem.title }}<UiIcon name="chevron-right" :size="13" /></router-link><span v-else-if="set.acCount===set.total" class="oj-set-phase practice"><UiIcon name="check" :size="14" />全部通过</span></div><div v-if="!set.items.length" class="oj-empty"><h2>比赛尚未开始</h2><p>开赛后展示题目</p></div><div v-else class="oj-set-problems"><div v-for="i in set.items" :key="i.id" :class="['oj-set-problem',{cancelled:!i.active}]"><OjProblemProgress :label="i.label" :progress="i.progress" /><div><h2>{{ i.title }} <span v-if="!i.active" class="oj-set-chip">已作废</span></h2><div class="oj-tags"><span v-for="t in i.tags" :key="t">{{ t }}</span><span>{{ i.modes.map(m=>modeNames[m]).join(' / ') }}</span></div><small v-if="!i.active">{{ i.cancelReason }}</small></div><span :class="['oj-difficulty',i.difficulty.toLowerCase()]"><i />{{ levels[i.difficulty] }}</span><router-link v-if="i.active" :to="`/oj/sets/${set.id}/items/${i.id}`" class="btn btn--secondary btn--sm">{{ set.canSubmit?'做题':'查看题目' }}<UiIcon name="chevron-right" :size="15" /></router-link></div></div></template>
      <section v-else-if="tab==='history'" class="oj-set-panel"><div class="oj-set-history-filters"><OjSelect v-model="mine" :options="scopeOptions" label="提交范围" @change="historyPage=1;loadHistory()" /><OjSelect v-model="itemId" :options="itemOptions" label="提交题目" @change="historyPage=1;loadHistory()" /><OjSelect v-model="language" :options="languages" label="提交语言" @change="historyPage=1;loadHistory()" /><OjSelect v-model="verdict" :options="statuses" label="判题结果" @change="historyPage=1;loadHistory()" /></div><p v-if="historyLoading" class="oj-console-hint" role="status">正在加载提交记录…</p><p v-else-if="!history.length" class="oj-console-hint">暂无提交记录</p><div v-for="r in history" :key="r.id" class="oj-set-history-row"><div><strong>{{ r.problemTitle }}</strong><small>{{ r.name }}（{{ r.nickname }}） · {{ r.studentId }}</small><small>{{ kindNames[r.kind] }} · {{ languageNames[r.language] }} · {{ modeNames[r.mode] }} · {{ date(r.acceptedAt) }}</small></div><OjStatusBadge :status="r.status" /><button class="btn btn--secondary btn--sm" :disabled="!r.canViewCode" @click="showCode(r)">{{ r.canViewCode?'查看代码':'代码未公开' }}</button></div><div v-if="historyTotal>50" class="oj-pagination"><button class="btn btn--secondary" :disabled="historyPage===1" @click="historyPage--;loadHistory()">上一页</button><span>{{ historyPage }} / {{ Math.ceil(historyTotal/50) }}</span><button class="btn btn--secondary" :disabled="historyPage*50>=historyTotal" @click="historyPage++;loadHistory()">下一页</button></div></section>
      <section v-else class="oj-set-panel"><div class="oj-ranking-heading"><h2>排名</h2><label class="oj-checkbox"><input v-model="completed" type="checkbox" @change="rankPage=1;loadRanking()" />仅显示完成全部题目</label></div><p v-if="rankLoading" class="oj-console-hint" role="status">正在更新排名…</p><p v-else-if="!ranking.length" class="oj-console-hint">暂无符合条件的参与者</p><div v-for="r in ranking" :key="r.userId" class="oj-set-rank-row"><span class="oj-rank" :class="{top:r.rank&&Number(r.rank)<=3}">{{ r.rank || '—' }}</span><div class="oj-set-rank-content"><div class="oj-set-rank-heading"><div class="oj-participant"><strong>{{ r.name }} <small>（{{ r.nickname }}）</small></strong><span class="oj-student-id">学号 / 账号 {{ r.studentId }}</span></div><span v-if="r.disqualified" class="oj-set-chip">不参与排名</span><div class="oj-solved-total"><strong>{{ r.acCount }}</strong><span>/ {{ rankTotals.total }}</span><small v-if="set.mode==='CONTEST'">罚时 {{ r.penalty }} 分钟</small><small v-else-if="r.completedAt">完成于 {{ date(r.completedAt) }}</small></div></div><div class="oj-difficulty-progress"><div v-for="d in difficultyStats" :key="d.key" :class="d.key"><span>{{ d.label }} <b>{{ r[d.key+'Ac'] }} / {{ rankTotals[d.key] }}</b></span><div class="oj-progress-track"><i :style="{width:progress(r[d.key+'Ac'],rankTotals[d.key])+'%'}" /></div></div></div><div class="oj-set-score-cells"><span v-for="i in activeItems" :key="i.id" :class="['oj-set-score-cell',{accepted:r.cells[i.id]?.accepted,pending:Number(r.cells[i.id]?.pending)>0,wrong:!r.cells[i.id]?.accepted&&Number(r.cells[i.id]?.wrong)>0}]" :title="i.title"><b>{{ i.label }}</b><small>{{ r.cells[i.id]?.accepted?'通过':Number(r.cells[i.id]?.pending)>0?'判题中':Number(r.cells[i.id]?.wrong)>0?'−'+r.cells[i.id].wrong:'—' }}</small><small v-if="set.mode==='CONTEST'&&r.cells[i.id]?.accepted">{{ r.cells[i.id].elapsedMinutes }} (+{{ r.cells[i.id].wrong }})</small></span></div></div></div><div v-if="rankTotal>50" class="oj-pagination"><button class="btn btn--secondary" :disabled="rankPage===1" @click="rankPage--;loadRanking()">上一页</button><span>{{ rankPage }} / {{ Math.ceil(rankTotal/50) }}</span><button class="btn btn--secondary" :disabled="rankPage*50>=rankTotal" @click="rankPage++;loadRanking()">下一页</button></div></section>
    </template>
    <dialog ref="codeDialog" class="oj-set-code-dialog"><header><h2>提交代码</h2><button class="btn btn--secondary btn--sm" @click="codeDialog.close()">关闭</button></header><p v-if="codeLoading" role="status">正在加载代码…</p><p v-if="codeError" class="oj-error">{{ codeError }}</p><template v-if="source"><p>{{ languageNames[source.language] }} · {{ modeNames[source.mode] }} <OjStatusBadge :status="source.status" /></p><OjCodeEditor :model-value="source.code" :language="source.language" read-only label="题单提交代码" /></template></dialog>
  </div>
</template>
<script setup>
import {ref,computed,onMounted,onBeforeUnmount} from 'vue'
import {useRoute,useRouter} from 'vue-router'
import request from '@/utils/request'
import PageHeader from '@/components/PageHeader.vue'
import UiIcon from '@/components/UiIcon.vue'
import OjProblemProgress from '@/components/OjProblemProgress.vue'
import OjSelect from '@/components/OjSelect.vue'
import OjStatusBadge from '@/components/OjStatusBadge.vue'
import OjCodeEditor from '@/components/OjCodeEditor.vue'
import {ojStatuses,languageNames,modeNames,kindNames} from '@/utils/ojDictionaries'
import './oj.css'
import './sets.css'
import './studio.css'
const route=useRoute(),router=useRouter(),base=`/api/oj/sets/${route.params.setId}`
const set=ref(null),loading=ref(true),refreshing=ref(false),joining=ref(false),error=ref(''),tab=ref(['ranking','history'].includes(route.query.tab)?route.query.tab:'problems')
const phases={PRACTICE:'练习中',UPCOMING:'未开始',RUNNING:'进行中',ENDED:'已结束',ARCHIVED:'已归档'},levels={EASY:'简单',MEDIUM:'中等',HARD:'困难'}
const tabs=[{value:'problems',label:'题目'},{value:'history',label:'提交记录'},{value:'ranking',label:'排名'}]
const date=t=>t?new Date(Number(t)).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false}):'未设置'
const clock=ref(Date.now());let offset=0,clockTimer,refreshTimer,disposed=false
const countdown=computed(()=>{const target=set.value?.phase==='UPCOMING'?set.value.startsAt:set.value?.endsAt;const seconds=Math.max(0,Math.floor((Number(target)-clock.value)/1000));return `${String(Math.floor(seconds/3600)).padStart(2,'0')}:${String(Math.floor(seconds/60)%60).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`})
const activeItems=computed(()=>set.value?.items.filter(i=>i.active)||[])
const resumeItem=computed(()=>activeItems.value.find(i=>i.progress?.state!=='AC'))
async function load(){try{const{data}=await request.get(base);if(disposed)return;set.value=data;offset=Number(data.serverNow)-Date.now();clock.value=Date.now()+offset;error.value=''}catch(e){error.value=e.message}finally{loading.value=false}}
async function join(){joining.value=true;try{await request.post(base+'/join');await load()}catch(e){error.value=e.message}finally{joining.value=false}}
async function refresh(){if(refreshing.value)return;refreshing.value=true;try{await load();await loadTab()}finally{refreshing.value=false}}
async function chooseTab(value){tab.value=value;router.replace({query:{...route.query,tab:value}});await loadTab()}
async function loadTab(){if(tab.value==='history')await loadHistory();if(tab.value==='ranking')await loadRanking()}
const history=ref([]),historyLoading=ref(false),historyTotal=ref(0),historyPage=ref(1),mine=ref('true'),itemId=ref(''),language=ref(''),verdict=ref('')
const scopeOptions=[{value:'true',label:'我的提交'},{value:'false',label:'全部提交'}]
const itemOptions=computed(()=>[{value:'',label:'全部题目'},...activeItems.value.map(i=>({value:String(i.id),label:`${i.label}. ${i.title}`}))])
const languages=[{value:'',label:'全部语言'},...Object.entries(languageNames).filter(([v])=>v!=='all').map(([value,label])=>({value,label}))]
const statuses=[{value:'',label:'全部结果'},...['AC','WA','CE','TLE','MLE','RE','OLE','SYSTEM_ERROR','QUEUED','RUNNING'].map(value=>({value,label:ojStatuses[value].label}))]
let historyGeneration=0,rankGeneration=0
async function loadHistory(){const generation=++historyGeneration;historyLoading.value=true;try{const{data}=await request.get(base+'/submissions',{params:{mine:mine.value,itemId:itemId.value||undefined,language:language.value,status:verdict.value,page:historyPage.value}});if(!disposed&&generation===historyGeneration){history.value=data.records;historyTotal.value=Number(data.total)}}catch(e){error.value=e.message}finally{if(generation===historyGeneration)historyLoading.value=false}}
const ranking=ref([]),rankLoading=ref(false),rankTotal=ref(0),rankPage=ref(1),completed=ref(false),rankTotals=ref({total:0,easy:0,medium:0,hard:0})
const difficultyStats=[{key:'easy',label:'简单'},{key:'medium',label:'中等'},{key:'hard',label:'困难'}]
const progress=(a,b)=>Number(b)>0?100*Number(a)/Number(b):0
async function loadRanking(){const generation=++rankGeneration;rankLoading.value=true;try{const{data}=await request.get(base+'/ranking',{params:{page:rankPage.value,completed:completed.value}});if(!disposed&&generation===rankGeneration){ranking.value=data.records;rankTotal.value=Number(data.total);rankTotals.value=data.totals}}catch(e){error.value=e.message}finally{if(generation===rankGeneration)rankLoading.value=false}}
const codeDialog=ref(null),source=ref(null),codeLoading=ref(false),codeError=ref('');let codeGeneration=0
async function showCode(row){const generation=++codeGeneration;source.value=null;codeError.value='';codeLoading.value=true;codeDialog.value.showModal();try{const{data}=await request.get(`${base}/submissions/${row.id}/code`);if(generation===codeGeneration&&!disposed)source.value=data}catch(e){codeError.value=e.message}finally{if(generation===codeGeneration)codeLoading.value=false}}
onMounted(async()=>{await load();if(disposed)return;await loadTab();if(disposed)return;clockTimer=setInterval(()=>{clock.value=Date.now()+offset;if(set.value?.mode==='CONTEST'&&['UPCOMING','RUNNING'].includes(set.value.phase)&&countdown.value==='00:00:00')load()},1000);refreshTimer=setInterval(()=>{if(!document.hidden)refresh()},15000)})
onBeforeUnmount(()=>{disposed=true;clearInterval(clockTimer);clearInterval(refreshTimer);historyGeneration++;rankGeneration++;codeGeneration++;codeDialog.value?.close()})
</script>
