package edu.csuft.sap.ui.icons

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.StrokeJoin
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.PathParser
import androidx.compose.ui.unit.dp

// Generated by scripts/generate_icons.py. Edit design/icons.json, then regenerate.
// 24dp grid · 1.75dp rounded strokes · shared geometry for SVG and native Compose.
object AppIcons {
    private fun build(
        name: String,
        strokes: List<String> = emptyList(),
        fills: List<String> = emptyList(),
        cutouts: List<String> = emptyList(),
        autoMirror: Boolean = false,
    ): ImageVector = ImageVector.Builder(
        name = name, defaultWidth = 24.dp, defaultHeight = 24.dp,
        viewportWidth = 24f, viewportHeight = 24f, autoMirror = autoMirror,
    ).apply {
        fills.forEach { d -> addPath(
            pathData = PathParser().parsePathString(d).toNodes(), fill = SolidColor(Color.Black),
        ) }
        cutouts.forEach { d -> addPath(
            pathData = PathParser().parsePathString(d).toNodes(),
            fill = SolidColor(Color.Black), pathFillType = PathFillType.EvenOdd,
        ) }
        strokes.forEach { d -> addPath(
            pathData = PathParser().parsePathString(d).toNodes(),
            stroke = SolidColor(Color.Black), strokeLineWidth = 1.75f,
            strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round,
        ) }
    }.build()

    /** 日历 */
    val Calendar: ImageVector by lazy {
        build("Calendar",
        strokes = listOf(
            "M7 4.5H17A3 3 0 0 1 20 7.5V18A3 3 0 0 1 17 21H7A3 3 0 0 1 4 18V7.5A3 3 0 0 1 7 4.5Z",
            "M8 3V6M16 3V6M4 9H20",
            "M8 13H8.1M12 13H12.1M16 13H16.1M8 17H8.1M12 17H12.1M16 17H16.1"
        ))
    }

    /** 日历 · 选中 */
    val CalendarFilled: ImageVector by lazy {
        build("CalendarFilled",
        strokes = listOf(
            "M8 3V5.5M16 3V5.5"
        ),
        cutouts = listOf(
            "M7 4.5H17A3 3 0 0 1 20 7.5V18A3 3 0 0 1 17 21H7A3 3 0 0 1 4 18V7.5A3 3 0 0 1 7 4.5Z M6 8H18V9.5H6Z M7 12H9V14H7Z M11 12H13V14H11Z M15 12H17V14H15Z M7 16H9V18H7Z M11 16H13V18H11Z M15 16H17V18H15Z"
        ))
    }

    /** 课表 */
    val Schedule: ImageVector by lazy {
        build("Schedule",
        strokes = listOf(
            "M7 4.5H17A3 3 0 0 1 20 7.5V18A3 3 0 0 1 17 21H7A3 3 0 0 1 4 18V7.5A3 3 0 0 1 7 4.5Z",
            "M8 3V6M16 3V6M4 9H20",
            "M8 12.5V17M12 12.5H16M12 16.5H16"
        ))
    }

    /** 课表 · 选中 */
    val ScheduleFilled: ImageVector by lazy {
        build("ScheduleFilled",
        strokes = listOf(
            "M8 3V5.5M16 3V5.5"
        ),
        cutouts = listOf(
            "M7 4.5H17A3 3 0 0 1 20 7.5V18A3 3 0 0 1 17 21H7A3 3 0 0 1 4 18V7.5A3 3 0 0 1 7 4.5Z M6 8H18V9.5H6Z M7 12H9V17.5H7Z M11.5 12H17V14H11.5Z M11.5 15.5H17V17.5H11.5Z"
        ))
    }

    /** 成绩 */
    val Grades: ImageVector by lazy {
        build("Grades",
        strokes = listOf(
            "M4 4V18A2 2 0 0 0 6 20H20",
            "M8 15V12M13 15V8M18 15V4"
        ))
    }

    /** 成绩 · 选中 */
    val GradesFilled: ImageVector by lazy {
        build("GradesFilled",
        strokes = listOf(
            "M4 4V18A2 2 0 0 0 6 20H20"
        ),
        fills = listOf(
            "M6.7 12A1.3 1.3 0 0 1 9.3 12V15A1.3 1.3 0 0 1 6.7 15Z",
            "M11.7 8A1.3 1.3 0 0 1 14.3 8V15A1.3 1.3 0 0 1 11.7 15Z",
            "M16.7 4A1.3 1.3 0 0 1 19.3 4V15A1.3 1.3 0 0 1 16.7 15Z"
        ))
    }

    /** 我的 */
    val Profile: ImageVector by lazy {
        build("Profile",
        strokes = listOf(
            "M8.5 7.5A3.5 3.5 0 1 0 15.5 7.5A3.5 3.5 0 1 0 8.5 7.5Z",
            "M5 20V18.5A4.5 4.5 0 0 1 9.5 14H14.5A4.5 4.5 0 0 1 19 18.5V20"
        ))
    }

    /** 我的 · 选中 */
    val ProfileFilled: ImageVector by lazy {
        build("ProfileFilled",
        fills = listOf(
            "M8 7.5A4 4 0 1 0 16 7.5A4 4 0 1 0 8 7.5Z",
            "M4.5 20V18.5A5 5 0 0 1 9.5 13.5H14.5A5 5 0 0 1 19.5 18.5V20A1 1 0 0 1 18.5 21H5.5A1 1 0 0 1 4.5 20Z"
        ))
    }

    /** 设置 */
    val Settings: ImageVector by lazy {
        build("Settings",
        strokes = listOf(
            "M4 7H7M12 7H20M4 17H12M17 17H20",
            "M7 7A2.5 2.5 0 1 0 12 7A2.5 2.5 0 1 0 7 7Z",
            "M12 17A2.5 2.5 0 1 0 17 17A2.5 2.5 0 1 0 12 17Z"
        ))
    }

    /** 设置 · 选中 */
    val SettingsFilled: ImageVector by lazy {
        build("SettingsFilled",
        strokes = listOf(
            "M4 7H20M4 17H20"
        ),
        fills = listOf(
            "M6 7A3.5 3.5 0 1 0 13 7A3.5 3.5 0 1 0 6 7Z",
            "M11 17A3.5 3.5 0 1 0 18 17A3.5 3.5 0 1 0 11 17Z"
        ))
    }

    /** 教务课表 */
    val Academic: ImageVector by lazy {
        build("Academic",
        strokes = listOf(
            "M3.5 8.5L12 4L20.5 8.5L12 13Z",
            "M7 11V16C9.5 18.5 14.5 18.5 17 16V11",
            "M20.5 8.5V16.5"
        ))
    }

    /** Web 课表 */
    val Web: ImageVector by lazy {
        build("Web",
        strokes = listOf(
            "M11 20H6A3 3 0 0 1 3 17V6A3 3 0 0 1 6 3H18A3 3 0 0 1 21 6V11",
            "M3 8H21M7 5.5H7.1M10 5.5H10.1",
            "M17 12V21M13.5 17.5L17 21L20.5 17.5"
        ))
    }

    /** 班级课表 */
    val ClassGroup: ImageVector by lazy {
        build("ClassGroup",
        strokes = listOf(
            "M9 7.5A3 3 0 1 0 15 7.5A3 3 0 1 0 9 7.5Z",
            "M6.5 20V18A4.5 4.5 0 0 1 11 13.5H13A4.5 4.5 0 0 1 17.5 18V20",
            "M5.5 5.5A2.5 2.5 0 0 0 5.5 10.5M18.5 5.5A2.5 2.5 0 0 1 18.5 10.5",
            "M5 14A3 3 0 0 0 2.5 17V18.5M19 14A3 3 0 0 1 21.5 17V18.5"
        ))
    }

    /** 添加 */
    val Add: ImageVector by lazy {
        build("Add",
        strokes = listOf(
            "M12 5V19M5 12H19"
        ))
    }

    /** 分享 */
    val Share: ImageVector by lazy {
        build("Share",
        strokes = listOf(
            "M8 12V17A3 3 0 0 0 11 20H18A3 3 0 0 0 21 17V12",
            "M3 12C3 7 7 6 12 6H15M11 2L15 6L11 10"
        ),
        autoMirror = true)
    }

    /** 同步 */
    val Refresh: ImageVector by lazy {
        build("Refresh",
        strokes = listOf(
            "M20 9A8 8 0 0 0 6.5 5.5L3.5 8.5M3.5 4.5V8.5H7.5",
            "M4 15A8 8 0 0 0 17.5 18.5L20.5 15.5M16.5 15.5H20.5V19.5"
        ))
    }

    /** 已选 */
    val Check: ImageVector by lazy {
        build("Check",
        strokes = listOf(
            "M5.5 12L10 16.5L18.5 7.5"
        ))
    }

    /** 展开 */
    val DropDown: ImageVector by lazy {
        build("DropDown",
        strokes = listOf(
            "M7 9.5L12 14.5L17 9.5"
        ))
    }

    /** 进入 */
    val ChevronRight: ImageVector by lazy {
        build("ChevronRight",
        strokes = listOf(
            "M9.5 6.5L15 12L9.5 17.5"
        ),
        autoMirror = true)
    }

    /** 返回 */
    val Back: ImageVector by lazy {
        build("Back",
        strokes = listOf(
            "M20 12H4M10 6L4 12L10 18"
        ),
        autoMirror = true)
    }

    /** 继续 */
    val ArrowRight: ImageVector by lazy {
        build("ArrowRight",
        strokes = listOf(
            "M4 12H20M14 6L20 12L14 18"
        ),
        autoMirror = true)
    }

    /** 密码 */
    val Lock: ImageVector by lazy {
        build("Lock",
        strokes = listOf(
            "M7 10V7A5 5 0 0 1 17 7V10",
            "M6.5 10H17.5A2 2 0 0 1 19.5 12V19A2 2 0 0 1 17.5 21H6.5A2 2 0 0 1 4.5 19V12A2 2 0 0 1 6.5 10Z",
            "M12 14V17"
        ))
    }

    /** 显示密码 */
    val Visibility: ImageVector by lazy {
        build("Visibility",
        strokes = listOf(
            "M2.5 12C5 7.5 8.2 5.5 12 5.5S19 7.5 21.5 12C19 16.5 15.8 18.5 12 18.5S5 16.5 2.5 12Z",
            "M9 12A3 3 0 1 0 15 12A3 3 0 1 0 9 12Z"
        ))
    }

    /** 隐藏密码 */
    val VisibilityOff: ImageVector by lazy {
        build("VisibilityOff",
        strokes = listOf(
            "M3 3L21 21M9.5 5.8C10.3 5.6 11.1 5.5 12 5.5C15.8 5.5 19 7.5 21.5 12C20.8 13.3 20 14.4 19.1 15.3",
            "M6.1 6.7C4.8 8 3.5 9.7 2.5 12C5 16.5 8.2 18.5 12 18.5C13.9 18.5 15.7 18 17.3 17",
            "M9 10A3.5 3.5 0 0 0 14 15"
        ))
    }

    /** 安全 */
    val Shield: ImageVector by lazy {
        build("Shield",
        strokes = listOf(
            "M12 3L20 6V11C20 15.5 17 19 12 21C7 19 4 15.5 4 11V6Z",
            "M8.5 11.5L11 14L15.5 9.5"
        ))
    }

    /** 关闭 */
    val Close: ImageVector by lazy {
        build("Close",
        strokes = listOf(
            "M6 6L18 18M18 6L6 18"
        ))
    }

    /** 公告与提醒 */
    val Bell: ImageVector by lazy {
        build("Bell",
        strokes = listOf(
            "M6 9A6 6 0 0 1 18 9V13L20 17H4L6 13Z",
            "M10 20C11 21 13 21 14 20M12 2V3"
        ))
    }

    /** 主题色 */
    val Palette: ImageVector by lazy {
        build("Palette",
        strokes = listOf(
            "M12 3A9 9 0 1 0 12 21H13A2 2 0 0 0 14.5 17.5A2 2 0 0 1 16 14H18A3 3 0 0 0 21 11C21 6.5 17 3 12 3Z",
            "M7 10H7.1M10 6.5H10.1M15 6.5H15.1M6.5 14.5H6.6"
        ))
    }

    /** 关于 */
    val Info: ImageVector by lazy {
        build("Info",
        strokes = listOf(
            "M3 12A9 9 0 1 0 21 12A9 9 0 1 0 3 12Z",
            "M12 11V16M12 7.5H12.1"
        ))
    }

    /** 意见反馈 */
    val Feedback: ImageVector by lazy {
        build("Feedback",
        strokes = listOf(
            "M7 4H17A4 4 0 0 1 21 8V14A4 4 0 0 1 17 18H9L4 21V17A4 4 0 0 1 3 14V8A4 4 0 0 1 7 4Z",
            "M7.5 9H16.5M7.5 13H13"
        ),
        autoMirror = true)
    }

    /** 更新日志 */
    val Update: ImageVector by lazy {
        build("Update",
        strokes = listOf(
            "M6.5 3H14L19 8V18A3 3 0 0 1 16 21H6.5A2.5 2.5 0 0 1 4 18.5V5.5A2.5 2.5 0 0 1 6.5 3Z",
            "M14 3V8H19M8 12H15M8 16H13"
        ))
    }

    /** 下载 */
    val Download: ImageVector by lazy {
        build("Download",
        strokes = listOf(
            "M12 3V15M7.5 10.5L12 15L16.5 10.5",
            "M4 16V18A3 3 0 0 0 7 21H17A3 3 0 0 0 20 18V16"
        ))
    }

    /** 退出 */
    val Logout: ImageVector by lazy {
        build("Logout",
        strokes = listOf(
            "M10 4H6A3 3 0 0 0 3 7V17A3 3 0 0 0 6 20H10",
            "M9 12H21M16.5 7.5L21 12L16.5 16.5"
        ),
        autoMirror = true)
    }

    /** 离线 */
    val CloudOff: ImageVector by lazy {
        build("CloudOff",
        strokes = listOf(
            "M3 3L21 21M8 8A6 6 0 0 0 6 12H5.5A3.5 3.5 0 0 0 5.5 19H15",
            "M11 5.2A6 6 0 0 1 18 10H18.5A4.5 4.5 0 0 1 21 18"
        ))
    }

    /** 搜索 */
    val Search: ImageVector by lazy {
        build("Search",
        strokes = listOf(
            "M3.5 10.5A7 7 0 1 0 17.5 10.5A7 7 0 1 0 3.5 10.5Z",
            "M16 16L21 21"
        ))
    }

    val catalog: List<Pair<String, ImageVector>> by lazy { listOf(
        "日历" to Calendar,
        "日历 · 选中" to CalendarFilled,
        "课表" to Schedule,
        "课表 · 选中" to ScheduleFilled,
        "成绩" to Grades,
        "成绩 · 选中" to GradesFilled,
        "我的" to Profile,
        "我的 · 选中" to ProfileFilled,
        "设置" to Settings,
        "设置 · 选中" to SettingsFilled,
        "教务课表" to Academic,
        "Web 课表" to Web,
        "班级课表" to ClassGroup,
        "添加" to Add,
        "分享" to Share,
        "同步" to Refresh,
        "已选" to Check,
        "展开" to DropDown,
        "进入" to ChevronRight,
        "返回" to Back,
        "继续" to ArrowRight,
        "密码" to Lock,
        "显示密码" to Visibility,
        "隐藏密码" to VisibilityOff,
        "安全" to Shield,
        "关闭" to Close,
        "公告与提醒" to Bell,
        "主题色" to Palette,
        "关于" to Info,
        "意见反馈" to Feedback,
        "更新日志" to Update,
        "下载" to Download,
        "退出" to Logout,
        "离线" to CloudOff,
        "搜索" to Search
    ) }
}
